Sheets Endpoint
ubclaunchpad/club-manager-server pull request #34
Opened 2020-11-16 20:35 UTC by KavpreetGrewal

Currently just using the API credentials from the JSON, but can be switched over once the OAuth is all set up.
Closes #29

2020-11-17 04:54 UTC, DConnorFong requested changes
Adding a general design suggestion - I think we should create a new model for a Sheet. It would contain the Sheet ID as well as the owner's email (replace with ID later).

This has the advantage that we can protect permissions to delete a sheet, and prevent duplicate additions.

Whenever we POST a new sheet, it would just check the sheet model to see if the ID exists, and if it does then just abort and return a 400.

2020-11-17 04:54 UTC, DConnorFong commented on src/controllers/sheets.ts
> +export const postSheet = async (req, res) => {
Warning for return type on function

2020-11-17 05:48 UTC, KavpreetGrewal commented
> Whenever we POST a new sheet, it would just check the sheet model to see if the ID exists, and if it does then just abort and return a 400

Would we then also have to check if the sheet has been edited? I guess it will work out better once we connect this with the database and then just perform checks on each applicant before adding.

2020-11-17 07:10 UTC, DConnorFong commented
> > Whenever we POST a new sheet, it would just check the sheet model to see if the ID exists, and if it does then just abort and return a 400
> 
> @DConnorFong Would we then also have to check if the sheet has been edited? I guess it will work out better once we connect this with the database and then just perform checks on each applicant before adding.

@KavpreetGrewal that's a pretty good point - its probably not a super important factor unless you wanted to split the logic into a function that assumes there are no applicants and a function that assumes there are some. The deleting is probably most important to enforce who has permissions to do certain authorities.

2020-11-23 06:05 UTC, DConnorFong approved these changes
LGTM

2020-11-23 16:12 UTC, merged